openapi: 3.0.0
info:
  title: NFT API Infura
  description: Query NFT data using Infura Nft Api ðŸš€
  contact: {}
  version: 0.0.1
servers:
- url: https://nft.api.infura.io
paths:
  /networks/{chainId}/nfts/transfers:
    get:
      tags:
      - Transfers
      summary: Gets all transfers from block to block
      description: Gets transfers from a block to block.
      operationId: NftsController_getTransfersfromBlockToBlock
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: fromBlock
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
        example: "16026179"
      - name: toBlock
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
        example: "16026190"
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/block/transfers:
    get:
      tags:
      - Transfers
      summary: Gets all transfers By block number or hash
      description: Gets transfers by block number or block hash.
      operationId: NftsController_getTransfersByBlockNumberOrHash
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: blockHashNumber
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: "16026179"
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/search:
    get:
      tags:
      - Metadata
      summary: Search for Nfts given a string
      description: Search for Nfts given a string
      operationId: NftsController_searchNfts
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: query
        in: query
        description: Query to search with
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: Cool Cats
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchNftModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}:
    get:
      tags:
      - Collections
      summary: Gets collection level metadata
      description: Gets the contract level metadata for a given contract address.
      operationId: NftsController_getCollectionMetadata
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/tokens:
    get:
      tags:
      - Collections
      summary: Gets all NFTs with metadata in a specific collection
      description: Gets all NFTs for a given contract address (including metadata).
      operationId: NftsController_getNftsForCollection
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x1A92f7381B9F03921564a437210bB9396471050C
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftModel'
      security:
      - basic: []
  /networks/{chainId}/accounts/{walletAddress}/assets/collections:
    get:
      tags:
      - Collections
      summary: Gets collections by wallet address
      description: Gets NFT collections owned by a given wallet address.
      operationId: NftsController_getCollectionsByWalletAddress
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: walletAddress
        in: path
        description: Wallet address of the owner of Nfts in collection
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionByWalletModel'
      security:
      - basic: []
  /networks/{chainId}/accounts/{walletAddress}/assets/nfts:
    get:
      tags:
      - Metadata
      summary: Gets all NFTs with metadata currently owned by a given wallet address
      description: Gets all NFTs owned by a given wallet address.
      operationId: NftsController_getNftsForAddress
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: walletAddress
        in: path
        description: Wallet address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/tokens/{tokenId}:
    get:
      tags:
      - Metadata
      summary: Gets NFT metadata
      description: Gets NFT data for the given NFT token ID and contract address.
      operationId: NftsController_getNftMetadata
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
      - name: tokenId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "7421"
      - name: resyncMetadata
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: "false"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataModel'
      security:
      - basic: []
  /networks/{chainId}/accounts/{walletAddress}/assets/transfers:
    get:
      tags:
      - Transfers
      summary: Gets all NFT transfers by wallet address
      description: Gets transfers of NFTs for a given wallet address
      operationId: NftsController_getTransferForAddress
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: walletAddress
        in: path
        description: Wallet address of the sender/recipient of the transfers
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/tokens/{tokenId}/transfers:
    get:
      tags:
      - Transfers
      summary: Gets all transfers for an NFT
      description: Gets transfers of an NFT by contract address and token ID.
      operationId: NftsController_getTransfersByTokenId
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x1A92f7381B9F03921564a437210bB9396471050C
      - name: tokenId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "7421"
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/transfers:
    get:
      tags:
      - Transfers
      summary: Gets all transfers By contract address
      description: Gets transfers by contract address.
      operationId: NftsController_getTransfersByTokenAddress
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x1A92f7381B9F03921564a437210bB9396471050C
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/owners:
    get:
      tags:
      - Ownership
      summary: Gets NFT owners by contract address
      description: ' Gets NFT owners given a token address'
      operationId: NftsController_getOwnersByContract
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x1A92f7381B9F03921564a437210bB9396471050C
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/{tokenId}/owners:
    get:
      tags:
      - Ownership
      summary: Gets NFT owners by contract address and tokenId
      description: Gets NFT owners for a specific token address and a tokenId
      operationId: NftsController_getOwnersByTokenId
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0x1A92f7381B9F03921564a437210bB9396471050C
      - name: tokenId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "0"
      - name: cursor
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnersModel'
      security:
      - basic: []
  /networks/{chainId}/nfts/{tokenAddress}/tradePrice:
    get:
      tags:
      - Market data
      summary: Gets the lowest ETH based price for the contract.
      operationId: NftsController_getTradePrice
      parameters:
      - name: chainId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "1"
      - name: tokenAddress
        in: path
        description: Contract address
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradePriceModel'
      security:
      - basic: []
components:
  schemas:
    TransfersResultsModel:
      required:
      - blockHash
      - blockNumber
      - blockTimestamp
      - contractType
      - fromAddress
      - price
      - quantity
      - toAddress
      - tokenAddress
      - tokenId
      - transactionHash
      - transactionType
      type: object
      properties:
        tokenAddress:
          type: string
          readOnly: true
          example: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        tokenId:
          type: string
          readOnly: true
          example: "3784"
        fromAddress:
          type: string
          readOnly: true
          example: 0x4f3a17060f14a28a1b706be652879d9aea4a83c2
        toAddress:
          type: string
          readOnly: true
          example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        contractType:
          type: string
          readOnly: true
          example: ERC1155
        price:
          type: string
          readOnly: true
          example: "0"
        quantity:
          type: string
          readOnly: true
          example: "1"
        blockNumber:
          type: string
          readOnly: true
          example: "14221791"
        blockTimestamp:
          type: string
          readOnly: true
          example: 2022-02-17T05:37:06.000Z
        blockHash:
          type: string
          readOnly: true
          example: 0x75cf7d327e259b10881cc3b66a4aad56eb2ab4163cc77a6c535123938aa87b5f
        transactionHash:
          type: string
          readOnly: true
          example: 0x97af3d5fe2951a3667dc9b465eb7253682e08d7ec23759722db1732fa9583468
        transactionType:
          type: string
          readOnly: true
          example: ""
      example:
        tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        transactionType: ""
        blockHash: 0x75cf7d327e259b10881cc3b66a4aad56eb2ab4163cc77a6c535123938aa87b5f
        quantity: "1"
        tokenId: "3784"
        contractType: ERC1155
        price: "0"
        blockNumber: "14221791"
        fromAddress: 0x4f3a17060f14a28a1b706be652879d9aea4a83c2
        blockTimestamp: 2022-02-17T05:37:06.000Z
        toAddress: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        transactionHash: 0x97af3d5fe2951a3667dc9b465eb7253682e08d7ec23759722db1732fa9583468
    TransfersModel:
      required:
      - account
      - cursor
      - network
      - pageNumber
      - pageSize
      - total
      - transfers
      type: object
      properties:
        total:
          type: number
          readOnly: true
          example: 1
        pageNumber:
          type: number
          readOnly: true
          example: 1
        pageSize:
          type: number
          readOnly: true
          example: 100
        network:
          type: string
          readOnly: true
          example: ETHEREUM
          enum:
          - ETHEREUM
          - GOERLI
          - SEPOLIA
          - BSC
          - POLYGON
          - MUMBAI
          - BSC TESTNET
          - AVALANCHE
          - AVALANCHE TESTNET
          - FANTOM
          - CRONOS
          - CRONOS TESTNET
          - PALM
          - ARBITRUM
        cursor:
          type: string
          readOnly: true
        account:
          type: string
          readOnly: true
          example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        transfers:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/TransfersResultsModel'
      example:
        cursor: cursor
        total: 1
        pageNumber: 1
        transfers:
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          transactionType: ""
          blockHash: 0x75cf7d327e259b10881cc3b66a4aad56eb2ab4163cc77a6c535123938aa87b5f
          quantity: "1"
          tokenId: "3784"
          contractType: ERC1155
          price: "0"
          blockNumber: "14221791"
          fromAddress: 0x4f3a17060f14a28a1b706be652879d9aea4a83c2
          blockTimestamp: 2022-02-17T05:37:06.000Z
          toAddress: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
          transactionHash: 0x97af3d5fe2951a3667dc9b465eb7253682e08d7ec23759722db1732fa9583468
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          transactionType: ""
          blockHash: 0x75cf7d327e259b10881cc3b66a4aad56eb2ab4163cc77a6c535123938aa87b5f
          quantity: "1"
          tokenId: "3784"
          contractType: ERC1155
          price: "0"
          blockNumber: "14221791"
          fromAddress: 0x4f3a17060f14a28a1b706be652879d9aea4a83c2
          blockTimestamp: 2022-02-17T05:37:06.000Z
          toAddress: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
          transactionHash: 0x97af3d5fe2951a3667dc9b465eb7253682e08d7ec23759722db1732fa9583468
        pageSize: 100
        account: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        network: ETHEREUM
    SearchNftResult:
      required:
      - blockNumberMinted
      - contractType
      - createdAt
      - metadata
      - minterAddress
      - tokenAddress
      - tokenHash
      - tokenId
      - transactionMinted
      type: object
      properties:
        tokenId:
          type: string
          readOnly: true
          example: "3784"
        tokenAddress:
          type: string
          readOnly: true
          example: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        metadata:
          type: string
          readOnly: true
          example: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
        contractType:
          type: string
          readOnly: true
          example: ERC1155
        tokenHash:
          type: string
          readOnly: true
          example: 003d3b164bf215e95871a094416622d2
        minterAddress:
          type: string
          readOnly: true
          example: 0x3b66c992860abd1ec94b917e222dca78ad55032f
        blockNumberMinted:
          type: string
          readOnly: true
          example: "12347180"
        transactionMinted:
          type: string
          readOnly: true
          example: 0x3b2da3a735babcb4fa12ca2f5f1a799f2344ce9042ea03716e554502c65aea0e
        createdAt:
          type: string
          readOnly: true
          example: 2017-12-04T09:14:19.000Z
      example:
        tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        blockNumberMinted: "12347180"
        createdAt: 2017-12-04T09:14:19.000Z
        metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
          ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
          trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\":\"\
          Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\":\"\
          Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\":\"Clothes\"\
          ,\"value\":\"Bandolier\"}]}"
        tokenId: "3784"
        contractType: ERC1155
        transactionMinted: 0x3b2da3a735babcb4fa12ca2f5f1a799f2344ce9042ea03716e554502c65aea0e
        minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
        tokenHash: 003d3b164bf215e95871a094416622d2
    SearchNftModel:
      required:
      - cursor
      - network
      - nfts
      - pageNumber
      - pageSize
      - total
      type: object
      properties:
        total:
          type: number
          readOnly: true
          example: 1
        pageNumber:
          type: number
          readOnly: true
          example: 1
        pageSize:
          type: number
          readOnly: true
          example: 100
        network:
          type: string
          readOnly: true
          example: ETHEREUM
          enum:
          - ETHEREUM
          - GOERLI
          - SEPOLIA
          - BSC
          - POLYGON
          - MUMBAI
          - BSC TESTNET
          - AVALANCHE
          - AVALANCHE TESTNET
          - FANTOM
          - CRONOS
          - CRONOS TESTNET
          - PALM
          - ARBITRUM
        cursor:
          type: string
          readOnly: true
        nfts:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/SearchNftResult'
      example:
        cursor: cursor
        total: 1
        pageNumber: 1
        nfts:
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          blockNumberMinted: "12347180"
          createdAt: 2017-12-04T09:14:19.000Z
          metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
          tokenId: "3784"
          contractType: ERC1155
          transactionMinted: 0x3b2da3a735babcb4fa12ca2f5f1a799f2344ce9042ea03716e554502c65aea0e
          minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
          tokenHash: 003d3b164bf215e95871a094416622d2
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          blockNumberMinted: "12347180"
          createdAt: 2017-12-04T09:14:19.000Z
          metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
          tokenId: "3784"
          contractType: ERC1155
          transactionMinted: 0x3b2da3a735babcb4fa12ca2f5f1a799f2344ce9042ea03716e554502c65aea0e
          minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
          tokenHash: 003d3b164bf215e95871a094416622d2
        pageSize: 100
        network: ETHEREUM
    CollectionModel:
      required:
      - contract
      - name
      - symbol
      - tokenType
      type: object
      properties:
        contract:
          type: string
          readOnly: true
          example: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
        name:
          type: string
          readOnly: true
          example: My Crypto NFT Project
        symbol:
          type: string
          readOnly: true
          example: CNSYS
        tokenType:
          type: string
          readOnly: true
          example: ERC-721
      example:
        symbol: CNSYS
        contract: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
        name: My Crypto NFT Project
        tokenType: ERC-721
    AssetsModel:
      required:
      - contract
      - supply
      - tokenId
      - type
      type: object
      properties:
        contract:
          type: string
          readOnly: true
          example: 0x8e04b34166612e73e8f8b7d7a5ddb6ea2895b4b5
        tokenId:
          type: string
          readOnly: true
          example: "3545"
        supply:
          type: string
          readOnly: true
          example: "1"
        type:
          type: string
          readOnly: true
          example: ERC721
        metadata:
          type: object
      example:
        metadata: {}
        tokenId: "3545"
        contract: 0x8e04b34166612e73e8f8b7d7a5ddb6ea2895b4b5
        type: ERC721
        supply: "1"
    NftModel:
      required:
      - account
      - assets
      - cursor
      - network
      - pageNumber
      - pageSize
      - total
      type: object
      properties:
        pageNumber:
          type: number
          readOnly: true
          example: 1
        pageSize:
          type: number
          readOnly: true
          example: 100
        network:
          type: string
          readOnly: true
          example: ETHEREUM
          enum:
          - ETHEREUM
          - GOERLI
          - SEPOLIA
          - BSC
          - POLYGON
          - MUMBAI
          - BSC TESTNET
          - AVALANCHE
          - AVALANCHE TESTNET
          - FANTOM
          - CRONOS
          - CRONOS TESTNET
          - PALM
          - ARBITRUM
        total:
          type: number
          readOnly: true
          example: 1
        account:
          type: string
          readOnly: true
          example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        cursor:
          type: string
          readOnly: true
        assets:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/AssetsModel'
      example:
        cursor: cursor
        total: 1
        pageNumber: 1
        assets:
        - metadata: {}
          tokenId: "3545"
          contract: 0x8e04b34166612e73e8f8b7d7a5ddb6ea2895b4b5
          type: ERC721
          supply: "1"
        - metadata: {}
          tokenId: "3545"
          contract: 0x8e04b34166612e73e8f8b7d7a5ddb6ea2895b4b5
          type: ERC721
          supply: "1"
        pageSize: 100
        account: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        network: ETHEREUM
    CollectionByWalletModel:
      required:
      - account
      - collections
      - cursor
      - network
      - pageNumber
      - pageSize
      - total
      type: object
      properties:
        pageNumber:
          type: number
          readOnly: true
          example: 1
        pageSize:
          type: number
          readOnly: true
          example: 100
        network:
          type: string
          readOnly: true
          example: ETHEREUM
          enum:
          - ETHEREUM
          - GOERLI
          - SEPOLIA
          - BSC
          - POLYGON
          - MUMBAI
          - BSC TESTNET
          - AVALANCHE
          - AVALANCHE TESTNET
          - FANTOM
          - CRONOS
          - CRONOS TESTNET
          - PALM
          - ARBITRUM
        cursor:
          type: string
          readOnly: true
        total:
          type: number
          readOnly: true
          example: 1
        account:
          type: string
          readOnly: true
          example: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        collections:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/CollectionModel'
      example:
        cursor: cursor
        total: 1
        pageNumber: 1
        collections:
        - symbol: CNSYS
          contract: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
          name: My Crypto NFT Project
          tokenType: ERC-721
        - symbol: CNSYS
          contract: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
          name: My Crypto NFT Project
          tokenType: ERC-721
        pageSize: 100
        account: 0x0a267cf51ef038fc00e71801f5a524aec06e4f07
        network: ETHEREUM
    MetadataModel:
      required:
      - contract
      - metadata
      - tokenId
      type: object
      properties:
        contract:
          type: string
          readOnly: true
          example: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
        tokenId:
          type: string
          readOnly: true
          example: "1"
        metadata:
          type: object
          readOnly: true
          example:
            name: "Washington #7421"
            description: "WeMint Cash First Edition: Washington #7421"
            attributes: []
      example:
        metadata:
          name: "Washington #7421"
          description: "WeMint Cash First Edition: Washington #7421"
          attributes: []
        tokenId: "1"
        contract: 0xa9cb55d05d3351dcd02dd5dc4614e764ce3e1d6e
    OwnersResultModel:
      required:
      - amount
      - blockNumber
      - blockNumberMinted
      - contractType
      - metadata
      - minterAddress
      - name
      - ownerOf
      - symbol
      - tokenAddress
      - tokenHash
      - tokenId
      type: object
      properties:
        tokenAddress:
          type: string
          readOnly: true
          example: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        tokenId:
          type: string
          readOnly: true
          example: "3784"
        amount:
          type: string
          readOnly: true
          example: "1"
        ownerOf:
          type: string
          readOnly: true
          example: 0x8252df1d8b29057d1afe3062bf5a64d503152bc8
        tokenHash:
          type: string
          readOnly: true
          example: 003d3b164bf215e95871a094416622d2
        blockNumberMinted:
          type: string
          readOnly: true
          example: "12347180"
        blockNumber:
          type: string
          readOnly: true
          example: "15839662"
        contractType:
          type: string
          readOnly: true
          example: ERC1155
        name:
          type: string
          readOnly: true
          example: BoredApeYachtClub
        symbol:
          type: string
          readOnly: true
          example: BAYC
        metadata:
          type: string
          readOnly: true
          example: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
        minterAddress:
          type: string
          readOnly: true
          example: 0x3b66c992860abd1ec94b917e222dca78ad55032f
      example:
        tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
        blockNumberMinted: "12347180"
        symbol: BAYC
        amount: "1"
        metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
          ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
          trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\":\"\
          Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\":\"\
          Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\":\"Clothes\"\
          ,\"value\":\"Bandolier\"}]}"
        tokenId: "3784"
        contractType: ERC1155
        blockNumber: "15839662"
        ownerOf: 0x8252df1d8b29057d1afe3062bf5a64d503152bc8
        name: BoredApeYachtClub
        minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
        tokenHash: 003d3b164bf215e95871a094416622d2
    OwnersModel:
      required:
      - cursor
      - network
      - owners
      - pageNumber
      - pageSize
      - total
      type: object
      properties:
        total:
          type: number
          readOnly: true
          example: 1
        pageNumber:
          type: number
          readOnly: true
          example: 1
        pageSize:
          type: number
          readOnly: true
          example: 100
        network:
          type: string
          readOnly: true
          example: ETHEREUM
          enum:
          - ETHEREUM
          - GOERLI
          - SEPOLIA
          - BSC
          - POLYGON
          - MUMBAI
          - BSC TESTNET
          - AVALANCHE
          - AVALANCHE TESTNET
          - FANTOM
          - CRONOS
          - CRONOS TESTNET
          - PALM
          - ARBITRUM
        cursor:
          type: string
          readOnly: true
        owners:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/OwnersResultModel'
      example:
        cursor: cursor
        total: 1
        pageNumber: 1
        pageSize: 100
        owners:
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          blockNumberMinted: "12347180"
          symbol: BAYC
          amount: "1"
          metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
          tokenId: "3784"
          contractType: ERC1155
          blockNumber: "15839662"
          ownerOf: 0x8252df1d8b29057d1afe3062bf5a64d503152bc8
          name: BoredApeYachtClub
          minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
          tokenHash: 003d3b164bf215e95871a094416622d2
        - tokenAddress: 0x082903f4e94c5e10a2b116a4284940a36afaed63
          blockNumberMinted: "12347180"
          symbol: BAYC
          amount: "1"
          metadata: "{\"image\":\"ipfs://QmQTquMHyYcBaXCS7bZccESzF2CoACtox9TmhRq38XJ6ey\"\
            ,\"attributes\":[{\"trait_type\":\"Eyes\",\"value\":\"Sunglasses\"},{\"\
            trait_type\":\"Background\",\"value\":\"Aquamarine\"},{\"trait_type\"\
            :\"Hat\",\"value\":\"Seaman's Hat\"},{\"trait_type\":\"Mouth\",\"value\"\
            :\"Rage\"},{\"trait_type\":\"Fur\",\"value\":\"Pink\"},{\"trait_type\"\
            :\"Clothes\",\"value\":\"Bandolier\"}]}"
          tokenId: "3784"
          contractType: ERC1155
          blockNumber: "15839662"
          ownerOf: 0x8252df1d8b29057d1afe3062bf5a64d503152bc8
          name: BoredApeYachtClub
          minterAddress: 0x3b66c992860abd1ec94b917e222dca78ad55032f
          tokenHash: 003d3b164bf215e95871a094416622d2
        network: ETHEREUM
    TradePriceModel:
      required:
      - blockHash
      - blockNumber
      - blockTimestamp
      - buyerAddress
      - marketplaceAddress
      - price
      - sellerAddress
      - tokenAddress
      - tokenIds
      - transactionHash
      type: object
      properties:
        transactionHash:
          type: string
          readOnly: true
          example: 0x0c930abb13c9b283bf73cdb979c8cb936bdf6189177d6f95beb892f66dc817fc
        blockTimestamp:
          type: string
          readOnly: true
          example: 2022-11-01T02:46:23.000Z
        blockHash:
          type: string
          readOnly: true
          example: 0x002096fc3b09e3b3c00fdb1d5c08cf20b442e5a99d15bdedc73ba3a2558ea132
        blockNumber:
          type: string
          readOnly: true
          example: "15872306"
        tokenIds:
          type: array
          readOnly: true
          example:
          - "7567"
          items:
            type: string
        sellerAddress:
          type: string
          readOnly: true
          example: 0xd279e2dd092835061fc6758d051bd78873ec7622
        buyerAddress:
          type: string
          readOnly: true
          example: 0x00000003dff73965674dbcc9dfcec53e1789ed50
        tokenAddress:
          type: string
          readOnly: true
          example: 0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d
        marketplaceAddress:
          type: string
          readOnly: true
          example: 0x00000000006c3852cbef3e08e8df289169ede581
        price:
          type: string
          readOnly: true
          example: "68100000000000000000"
      example:
        tokenAddress: 0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d
        marketplaceAddress: 0x00000000006c3852cbef3e08e8df289169ede581
        blockHash: 0x002096fc3b09e3b3c00fdb1d5c08cf20b442e5a99d15bdedc73ba3a2558ea132
        buyerAddress: 0x00000003dff73965674dbcc9dfcec53e1789ed50
        price: "68100000000000000000"
        blockNumber: "15872306"
        blockTimestamp: 2022-11-01T02:46:23.000Z
        sellerAddress: 0xd279e2dd092835061fc6758d051bd78873ec7622
        tokenIds:
        - "7567"
        transactionHash: 0x0c930abb13c9b283bf73cdb979c8cb936bdf6189177d6f95beb892f66dc817fc
  securitySchemes:
    basic:
      type: http
      scheme: basic
